### ISSUE TITLE
Magento 2.3.5

### ISSUE THREAD

**Issue by pigorg** [experius/Magento-2-Module-Experius-Address-Lines#19]
Not work with magento 2.3.5

**Comment by akosglue** [comment]
is there a solution?

**Comment by akosglue** [comment]
it might be the case the there are labels actually but they are not visible because of the CSS.

**Comment by borisvankatwijk** [comment]
@pigorg , @akosglue ,

The module is now fully updated to Magento 2.4.6 standards.
The styling is indeed the reason the label isn't visible. Which is still the case in the new version (for luma theme).
